
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UslugaBIRzewnPubl", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://raw.githubusercontent.com/freshmindpl/wyszukiwarkaregon/master/wsdl/UslugaBIRzewnPubl.xsd")
public class UslugaBIRzewnPubl extends Service {

    private final static URL USLUGABIRZEWNPUBL_WSDL_LOCATION;
    private final static WebServiceException USLUGABIRZEWNPUBL_EXCEPTION;
    private final static QName USLUGABIRZEWNPUBL_QNAME = new QName("http://tempuri.org/", "UslugaBIRzewnPubl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://raw.githubusercontent.com/freshmindpl/wyszukiwarkaregon/master/wsdl/UslugaBIRzewnPubl.xsd");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USLUGABIRZEWNPUBL_WSDL_LOCATION = url;
        USLUGABIRZEWNPUBL_EXCEPTION = e;
    }

    public UslugaBIRzewnPubl() {
        super(__getWsdlLocation(), USLUGABIRZEWNPUBL_QNAME);
    }

    public UslugaBIRzewnPubl(WebServiceFeature... features) {
        super(__getWsdlLocation(), USLUGABIRZEWNPUBL_QNAME, features);
    }

    public UslugaBIRzewnPubl(URL wsdlLocation) {
        super(wsdlLocation, USLUGABIRZEWNPUBL_QNAME);
    }

    public UslugaBIRzewnPubl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USLUGABIRZEWNPUBL_QNAME, features);
    }

    public UslugaBIRzewnPubl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UslugaBIRzewnPubl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUslugaBIRzewnPubl
     */
    @WebEndpoint(name = "e3")
    public IUslugaBIRzewnPubl getE3() {
        return super.getPort(new QName("http://tempuri.org/", "e3"), IUslugaBIRzewnPubl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUslugaBIRzewnPubl
     */
    @WebEndpoint(name = "e3")
    public IUslugaBIRzewnPubl getE3(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "e3"), IUslugaBIRzewnPubl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USLUGABIRZEWNPUBL_EXCEPTION!= null) {
            throw USLUGABIRZEWNPUBL_EXCEPTION;
        }
        return USLUGABIRZEWNPUBL_WSDL_LOCATION;
    }

}
