generateWSDL:
	 wsimport -b ../resources/wsdl/schema.wsdl -B-XautoNameResolution  -extension -J-Djavax.xml.accessExternalSchema=all -J-Djavax.xml.accessExternalDTD=all -keep -verbose -XadditionalHeaders -Xnocompile https://raw.githubusercontent.com/freshmindpl/wyszukiwarkaregon/master/wsdl/UslugaBIRzewnPubl.xsd

